using System.Text.Json.Serialization;
using Pxl8.Contracts.Abstractions;

namespace Pxl8.Contracts.V1.PolicySnapshot;

/// <summary>
/// Policy snapshot - atomic configuration bundle for Data Plane
/// </summary>
/// <remarks>
/// Generated by Control Plane every 60s, consumed by Data Planes.
/// Contains all tenant configs, quotas, domains, and API keys.
/// Spec: ARCHITECTURE_SPLIT.md - Policy Snapshot Contract
/// </remarks>
public record PolicySnapshotDto : IVersioned
{
    /// <summary>
    /// Unique snapshot identifier (for cache invalidation)
    /// </summary>
    [JsonPropertyName("snapshot_id")]
    public required Guid SnapshotId { get; init; }

    /// <summary>
    /// Contract version (semantic versioning major)
    /// </summary>
    [JsonPropertyName("version")]
    public int Version { get; init; } = 1;

    /// <summary>
    /// Snapshot generation timestamp (UTC)
    /// </summary>
    [JsonPropertyName("generated_at")]
    public required DateTimeOffset GeneratedAt { get; init; }

    /// <summary>
    /// All active tenant policies
    /// </summary>
    [JsonPropertyName("tenants")]
    public required IReadOnlyList<TenantPolicyDto> Tenants { get; init; }
}
